services:
  - type: web
    name: blog-backend
    runtime: node
    buildCommand: cd Backend && npm install
    start: node server.js
    branch: master
    plan: free
    envVars:
      - key: MONGO_URL
      value: false

    - type: web
    name: blog-frontend
    runtime: node
    buildCommand: npm install && npm run build
    start: npm run preview
    branch: master
    plan: free


  