services:
  - type: web
    name: blog-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    branch: main
    plan: free
    envVars:
      - key: MONGO_URL
        value: your-mongo-uri-here

  - type: web
    name: blog-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    branch: main
